<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Build-JsonValidator</RootNamespace>
    <AssemblyName>Build-JsonValidator</AssemblyName>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <Version>1.0.2</Version>
    <FileVersion>1.0.2</FileVersion>
    <InformationalVersion>1.0.2+9c1f47c2a3c72de5bb518834823976f5b0424780</InformationalVersion>
    <PackageVersion>1.0.2</PackageVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.PowerShell.SDK" Version="7.4.6" />
    <PackageReference Include="Newtonsoft.Json.Schema" Version="4.0.1" />
  </ItemGroup>

</Project>